RDKCOM-3462 RDKBCMF-298 CcspWifiAgent Build Failure when webconfig_bin is e...
CcspWifiAgent Build Failure when webconfig_bin DISTRO FEATURE is enabled:
CcspWifiAgent/source/TR-181/sbapi/wifi_webconfig.c:2341:20: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
 2341 |     CcspTraceInfo((%s:Msg unpack success. Offset is %lu\n, {}FUNCTION{},offset));
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~               ~~~~~~
      |                                                                           |
      |                                                                           size_t {aka unsigned int}
CcspWifiAgent/source/TR-181/sbapi/wifi_webconfig.c:2469:33: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'uint64_t' {aka 'long long unsigned int'} [-Werror=format=]
 2469 |                 CcspTraceError((Version type %d version %lu\n,map_ptr->val.type,ps->version));
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ~~~~~~~~~~~
      |                                                                                     |
      |                                                                                     uint64_t {aka long long unsigned int}
CcspWifiAgent/source/TR-181/sbapi/wifi_webconfig.c:5128:20: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
 5128 |     CcspTraceInfo((%s:Msg unpack success. Offset is %lu\n, {}FUNCTION{},offset));
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~               ~~~~~~
      |                                                                           |
      |                                                                           size_t {aka unsigned int}
CcspWifiAgent/source/TR-181/sbapi/wifi_webconfig.c:5159:32: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'uint64_t' {aka 'long long unsigned int'} [-Werror=format=]
 5159 |                 CcspTraceInfo((Version type %d version %lu\n,map_ptr->val.type,vap_data->version));
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ~~~~~~~~~~~~~~~~~
      |                                                                                          |
      |                                                                                          uint64_t {aka long long unsigned int}

Reason for change: RDKBCMF-298 CcspWifiAgent Build Failure when webconfig_bin is e...
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen_barrett@comcast.com>

(cherry picked from commit 87aacd6bdfddee66eac76008dba85c42b2d403e5)
Change-Id: Id2f4f98486ff4ccedd46a9d0d6970c6a82cac740