RDKCOM-3750 RDKBCMF-310 Build errors in CcspWifiAgent
Build errors in CcspWifiAgent as a result of CcspWifiAgent/+/82697:
| CcspWifiAgent/source/TR-181/sbapi/cosa_wifi_apis.c:9754:10: error: unused variable 'pRadius_greylist_Enabled' [-Werror=unused-variable]
|  9754 |     BOOL pRadius_greylist_Enabled = FALSE;
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~

Reason for change: RDKBCMF-310 Build errors in CcspWifiAgent
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen_barrett@comcast.com>

(cherry picked from commit 8478c36012f8d843245c94ca6fe88eb93c71db74)
Change-Id: Id96d2d7b2daac9fecf158f5774b03b690a088d67